### ISSUE TITLE
[Bug] Crash on 1.18.2 when Mythic Metals 0.13.1 is present

### ISSUE THREAD

**Issue by ENDERZOMBI102** [LordDeatHunter/HarvestScythes#31]
When loading in an environment with Mythic Metals 0.13.1 the game will crash with a `java.lang.NoSuchFieldError` when items are loaded, removing MythicMetals prevents the crash as expected.

Full stack trace
```
java.lang.NoSuchFieldError: STEEL
	at wraith.harvest_scythes.support.MythicMetalsSupport.loadItems(MythicMetalsSupport.java:38)
	at wraith.harvest_scythes.HarvestScythes.load(HarvestScythes.java:64)
	at net.minecraft.class_310.handler$bof000$inject(class_310.java:11447)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by Noaaan** [comment]
Which version of Harvest Scythes are you using? The compat was updated back in march in regards to Steel tools/gear being removed.

**Comment by ENDERZOMBI102** [comment]
sorry for the late response, i'm using 2.4.0

**Comment by LordDeatHunter** [comment]
Latest for 1.18.1 is HS 2.4.1
Latest for 1.18.2 is HS 2.5.0
Update the mod to the latest version.

**Comment by ENDERZOMBI102** [comment]
modrinth must have screwd me over, thanks!
