### ISSUE TITLE
Suggestion: Enhanced Compatibility with Farmer's Delight / Expanded Delight Crops

### ISSUE THREAD

**Issue by bbbower** [LordDeatHunter/HarvestScythes#38]
I've noticed very mixed results with farmers delight crops from breaking crops like rice completely to reverting tomato's to its initial planted state.  Just suggesting tweaking behavior for this mods crops would be a nice enhancement.

**Comment by Geethebluesky** [comment]
I confirm the scythes will break the rice crop out of the ground completely (needs manual replanting), I'm on Fabric 1.18.2, latest version of this mod (2.5.1) and using Farmer's Delight 0.2.1.

**Comment by Bob74** [comment]
On server there is also a rendering issue when you harvest onions or cabbages. The one you target will be updated but the ones that are in the area of effect of the scythe will be rendered as mature while they actually are replanted.

It generates this error on the client side only:
```
[22:57:05] [Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26204()" because "$$1" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
	at net.minecraft.world.World.setBlockState(World:210) ~[?:?]
	at net.minecraft.world.World.setBlockState(World:196) ~[?:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.method_34007(ClientPlayNetworkHandler:650) ~[?:?]
	at net.minecraft.network.packet.s2c.play.ChunkDeltaUpdateS2CPacket.visitUpdates(ChunkDeltaUpdateS2CPacket:72) ~[?:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onChunkDeltaUpdate(ClientPlayNetworkHandler:650) ~[?:?]
	at net.minecraft.network.packet.s2c.play.ChunkDeltaUpdateS2CPacket.apply(ChunkDeltaUpdateS2CPacket:64) ~[?:?]
	at net.minecraft.network.packet.s2c.play.ChunkDeltaUpdateS2CPacket.apply(ChunkDeltaUpdateS2CPacket:14) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:116) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1085) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.10.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

Also, the harvested plants give only 1 item using a scythe while they give more when broken by hand (this applies at least to both Bewitchment and FarmersDelight).
